### ISSUE TITLE
nsb13, show hide watcher in quarter size stage leaves light grey line

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#103]
When hiding a watcher in quarter size stage, a light grey line stays on the stage. Best seen if stage background is black or white.
Minor bug,

**Comment by timrowledge** [comment]
Once the locus of calculating the damage area caused by hiding or dragging there Watcher is found - ScratchStageMorph>invalidRect:from: - it is easy to see that we need to round the scaled damage area outwards. This just requires truncating the processed origin co-ordinate and ceiling-ing (clumsy phrase) the extent co-ordinates.

**Comment by timrowledge** [comment]
Appears to work nicely. Fixed in Scratch-tpr.312
