### ISSUE TITLE
nuscratch15: presentation mode, list display, slider not draggable

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#126]
create a list with a few entries (till a slider is shown)
switch to presentation mode
slider is not draggable

in legacy winscratch and old scratch, slider is draggable.

**Comment by timrowledge** [comment]
My mistake; when making the other presentation mode fixes some time ago I got over-enthusiatic and accidentally locked up the list morph.
Working on sorting that out...

**Comment by timrowledge** [comment]
Removed the over-enthusiastic ScratchListMorph>isLocked method so that events get passed on properly. Add a cleaner test for being-in-an-offscreen-world (Morph>isOffscreenWorld etc.) Use that test in ScratchListMorph>handlesMouseDown: and ListMultilineStringMorph>mouseDown: so that only the slider functions.

**Comment by timrowledge** [comment]
Fixed in Scratch-tpr.240
