### ISSUE TITLE
variable watcher inconsistent length truncation

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#130]
When having long string variable, the watcher seems to truncate displayed length to 64. This is reasonable (although old scratch tries to display even very long variables). But the watcher frame is still of a size as if the variable would be displayed completely.

Expected: The watcher frame width should be limited too.
Category: minor issue

Appended a simple script.
![double](https://cloud.githubusercontent.com/assets/5240331/6650876/cdec2e16-ca28-11e4-9e5d-f0d8a1fb5b76.gif)

**Comment by timrowledge** [comment]
It seems much more sensible to let the display actually show as much of the value as can fit, so that's what I've arranged.The limiting factor here was a slightly strange choice of default maximum width in the superclass of UpdatingScratchStringMorph; now we set our own value and use the ScratchFrameMorph>workpane extent x

**Comment by timrowledge** [comment]
Fixed in Scratch-tpr.303
