### ISSUE TITLE
scratch-2015-07-18, new broadcast event, popup text

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#140]
editing broadcast events brings up (Neu/edit...) in german, (new/edit...) in english. 
Expected: (new...)

**Comment by timrowledge** [comment]
This is an attempt to show that we can now edit broadcast strings (to correct a spelling or number mistake, for example) rather than having to enter a new one from the beginning. I hope this will make life a bit easier!
As a guess at how to make it clear that editing is possible I changed the menu entry; I don't think 'edit' is in the translation dictionaries (yet) so it will not get localised.
