### ISSUE TITLE
20160824, hide sprite with think bubble

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#211]
sprite gets hidden, but bubble stays visible.
In legacy scratch, both disappear.

Very funny: hide; wait (10); think 'where I am?' shows bubble only.

**Comment by timrowledge** [comment]
Oh my, not a good thing to do.
Fortunately quite easy to work out the problem here; when we display the stage submorphs we first display all the sprites and then separately look at all their submorphs to handle just the talk bubbles. That code was for some reason ignoring the visibility state of the sprite. Once corrected the bubble pops when we hide the sprite.
Nice catch.

**Comment by timrowledge** [comment]
Fixed inNuScrtch-tpr.364
