### ISSUE TITLE
20160824 command line start, terminate program by window 'X'

### ISSUE THREAD

**Issue by heppg** [raspberrypi/scratch#216]
Start a program on command line
example: scratch 'Documents/Scratch Programs/test.sb'
Terminate program by click on X in window title.
![2016-09-03-084725_1824x984_scrot](https://cloud.githubusercontent.com/assets/5240331/18223390/7672ac6e-71b6-11e6-88e1-939fc6cef021.png)

Same setup, but terminate program by 'file/quit' is perfect.

**Comment by timrowledge** [comment]
Hmm, interesting. What happens here is that a WindowEvent is passed in by the VM to handle the X close and it somehow ends up being queried for 'position' by the Scratch stage. Quite how that happens is a mystery right now. Let's take a look.

**Comment by timrowledge** [comment]
Oh, of course. The WindowEvent is raised by the VM as a result of clicking on the window's X button, which is caught by the windowEventHandler I install as part of the release build. This passes the WindowEvent on to ScratchFrameMorph, which ends up using ScratchCloseDialog>getUserResponse. As part of the somewhat tacky modal dialogue handling in Morphic the various submorphs in the Scratch application get to do their stepping which includes the little mouse position stringmorphs wanting to display the latest mouse x/y.

This is a side-effect of some changes to event handling in Squeak 5.1 that means we should be using 'lastEvent' in ScriptableScratchMorph>>mouseX/Y instead of 'currentEvent'. Damn.

**Comment by timrowledge** [comment]
Fixed in NuScratch-tpr.363
Replaced more (mis)uses of currentEvent by either currentHand lastEvent or by pushing the actual event down the stack.
